# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true

- task: Xcode@5
  displayName: 'Running XCTest/XCUITest'
  inputs:
    actions: 'test'
    scheme: 'sampleapp-ios-swift'
    sdk: 'iphonesimulator'
    configuration: 'Release'
    xcodeVersion: 'default' # Options: 8, 9, default, specifyPath
    packageApp: false
    xcWorkspacePath: '*.xcworkspace'
    destinationSimulators: 'iPhone 14'
    destinationTypeOption: 'simulators'
    destinationPlatformOption: 'iOS'
    signingOption: "auto"
    useXcpretty: true
    publishJUnitResults: true


#- task: Xcode@5
#  displayName: 'Running XCode build'
#  inputs:
#    actions: 'clean build'
#    configuration: 'Release'
#    sdk: 'iphoneos'
#    xcWorkspacePath: '*.xcworkspace'
#    scheme: 'sampleapp-ios-swift'
#    packageApp: false
#    publishJUnitResults: true
#    ask: Xcode@5
